### ISSUE TITLE
IDEEA Installation Issue

### ISSUE THREAD

**Issue by sourishju** [ideea-model/IDEEA#3]
**Showing Error when running  the command:**           
` pkg_install("ideea-model/IDEEA") `

**ERROR:**

→ Will install 1 package.
→ The package (0 B) is cached.
+ IDEEA   0.0.21.9000 [bld][cmp] (GitHub: af3174e)
ℹ No downloads are needed, 1 pkg is cached
✖ Failed to download IDEEA 0.0.21.9000 (source)
Error: 
! error in pak subprocess
Caused by error: 
! Failed to download IDEEA from `https://api.github.com/repos/ideea-model/IDEEA/zipball/af3174e6da5fbd22158c2722292f0520f805d5bd`.
---
Backtrace:
1. pak::pkg_install("ideea-model/IDEEA")
2. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("...
3. err$throw(res$error)
---
Subprocess backtrace:
1. base::withCallingHandlers(cli_message = function(msg) { ...
2. get("pkg_install_do_plan", asNamespace("pak"))(...)
3. proposal$stop_for_download_error()
4. private$plan$stop_for_solution_download_error()
5. pkgdepends:::pkgplan_stop_for_solution_download_error(self, private)
6. pkgdepends:::stop(err)
7. | base::throw(add_class(args[[1]], c("rlib_error_3_0", "rlib_error"),...
8. | base::signalCondition(cond)
9. global (function (e) ...

**Comment by olugovoy** [comment]
Yes, I'm having the same issue - something wrong with .rda file version, trying to figure out, thx!

**Comment by olugovoy** [comment]
This is probably it (data files are too large for a standard R-package):
https://forum.posit.co/t/installing-a-package-that-uses-git-lfs-to-store-large-files/8915/2
We need to move large files to Zenodo to be able to streamline installation of IDEEA from GitHub.

**Comment by olugovoy** [comment]
@sourishju, please try again - it worked for me. The updated version is 22:
"IDEEA version: 0.0.22.9000 (2024-04-10)"

**Comment by sourishju** [comment]
Now the problem is resolved

**Comment by sourishju** [comment]
AS THE PROBLEM IS RESOLVED.. CLOSING THIS ISSUE
