### ISSUE TITLE
MINICONDA INSTALLATION WHEN A PREVIOUS VERSION IS ALREADY INSTALLED

### ISSUE THREAD

**Issue by sourishju** [ideea-model/IDEEA#5]
I am having an issue installing miniconda.. install_miniconda..... Miniconda is already there in my computer, installed for switch and pypsa... but when i am trying to install with command install_miniconda... the following error is showing:

Error: Error creating conda environment 'r-reticulate' [exit code 1]

* Installing Miniconda -- please wait a moment ...
* Downloading "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe" ...
Warning in download.file(url, destfile = installer, mode = "wb") :
  the 'wininet' method is deprecated for http:// and https:// URLs
trying URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe'
Content type 'application/octet-stream' length 81940440 bytes (78.1 MB)
downloaded 78.1 MB

+ "C:/Users/Sourish/AppData/Local/r-miniconda/condabin/conda.bat" update --yes --name base conda
Retrieving notices: ...working... done
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Sourish\AppData\Local\R-MINI~1

  added / updated specs:
    - conda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    archspec-0.2.3             |     pyhd3eb1b0_0          47 KB
    ca-certificates-2024.3.11  |       haa95532_0         128 KB
    conda-24.3.0               |  py312haa95532_0         1.2 MB
    ------------------------------------------------------------
                                           Total:         1.3 MB

The following packages will be UPDATED:

  archspec                               0.2.1-pyhd3eb1b0_0 --> 0.2.3-pyhd3eb1b0_0 
  ca-certificates                     2023.12.12-haa95532_0 --> 2024.3.11-haa95532_0 
  conda                              24.1.2-py312haa95532_0 --> 24.3.0-py312haa95532_0 

Downloading and Extracting Packages: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ "C:/Users/Sourish/AppData/Local/r-miniconda/condabin/conda.bat" "create" "--yes" "--name" "r-reticulate" "python=3.9" "numpy" "--quiet" "-c" "conda-forge"
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/openssl-3.2.1-hcfcfb64_1.conda>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/openssl-3.2.1-hcfcfb64_1.conda>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

## Package Plan ##

  environment location: C:\Users\Sourish\AppData\Local\R-MINI~1\envs\r-reticulate

  added / updated specs:
    - numpy
    - python=3.9

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       hcfcfb64_5         122 KB  conda-forge
    intel-openmp-2024.1.0      |     h57928b3_964         1.5 MB  conda-forge
    libblas-3.9.0              |     22_win64_mkl         4.9 MB  conda-forge
    libcblas-3.9.0             |     22_win64_mkl         5.0 MB  conda-forge
    libhwloc-2.9.3             |default_haede6df_1009         2.5 MB  conda-forge
    libiconv-1.17              |       hcfcfb64_2         621 KB  conda-forge
    liblapack-3.9.0            |     22_win64_mkl         4.9 MB  conda-forge
    libsqlite-3.45.2           |       hcfcfb64_0         849 KB  conda-forge
    libxml2-2.12.6             |       hc3477c8_1         1.6 MB  conda-forge
    libzlib-1.2.13             |       hcfcfb64_5          54 KB  conda-forge
    mkl-2024.1.0               |     h66d3029_692       104.4 MB  conda-forge
    numpy-1.26.4               |   py39hddb5d58_0         5.6 MB  conda-forge
    openssl-3.2.1              |       hcfcfb64_1         7.8 MB  conda-forge
    pip-24.0                   |     pyhd8ed1ab_0         1.3 MB  conda-forge
    pthreads-win32-2.9.1       |       hfa6e2cd_3         141 KB  conda-forge
    python-3.9.19              |h4de0772_0_cpython        16.1 MB  conda-forge
    python_abi-3.9             |           4_cp39           7 KB  conda-forge
    setuptools-69.2.0          |     pyhd8ed1ab_0         460 KB  conda-forge
    tbb-2021.11.0              |       h91493d7_1         158 KB  conda-forge
    tk-8.6.13                  |       h5226925_1         3.3 MB  conda-forge
    tzdata-2024a               |       h0c530f3_0         117 KB  conda-forge
    ucrt-10.0.22621.0          |       h57928b3_0         1.2 MB  conda-forge
    vc-14.3                    |      hcf57466_18          17 KB  conda-forge
    vc14_runtime-14.38.33130   |      h82b7239_18         732 KB  conda-forge
    vs2015_runtime-14.38.33130 |      hcb4865c_18          17 KB  conda-forge
    wheel-0.43.0               |     pyhd8ed1ab_1          57 KB  conda-forge
    xz-5.4.6                   |       h8cc25b3_0         587 KB
    ------------------------------------------------------------
                                           Total:       164.2 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-hcfcfb64_5 
  ca-certificates    pkgs/main/win-64::ca-certificates-2024.3.11-haa95532_0 
  intel-openmp       conda-forge/win-64::intel-openmp-2024.1.0-h57928b3_964 
  libblas            conda-forge/win-64::libblas-3.9.0-22_win64_mkl 
  libcblas           conda-forge/win-64::libcblas-3.9.0-22_win64_mkl 
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_0 
  libhwloc           conda-forge/win-64::libhwloc-2.9.3-default_haede6df_1009 
  libiconv           conda-forge/win-64::libiconv-1.17-hcfcfb64_2 
  liblapack          conda-forge/win-64::liblapack-3.9.0-22_win64_mkl 
  libsqlite          conda-forge/win-64::libsqlite-3.45.2-hcfcfb64_0 
  libxml2            conda-forge/win-64::libxml2-2.12.6-hc3477c8_1 
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_5 
  mkl                conda-forge/win-64::mkl-2024.1.0-h66d3029_692 
  numpy              conda-forge/win-64::numpy-1.26.4-py39hddb5d58_0 
  openssl            conda-forge/win-64::openssl-3.2.1-hcfcfb64_1 
  pip                conda-forge/noarch::pip-24.0-pyhd8ed1ab_0 
  pthreads-win32     conda-forge/win-64::pthreads-win32-2.9.1-hfa6e2cd_3 
  python             conda-forge/win-64::python-3.9.19-h4de0772_0_cpython 
  python_abi         conda-forge/win-64::python_abi-3.9-4_cp39 
  setuptools         conda-forge/noarch::setuptools-69.2.0-pyhd8ed1ab_0 
  tbb                conda-forge/win-64::tbb-2021.11.0-h91493d7_1 
  tk                 conda-forge/win-64::tk-8.6.13-h5226925_1 
  tzdata             conda-forge/noarch::tzdata-2024a-h0c530f3_0 
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0 
  vc                 conda-forge/win-64::vc-14.3-hcf57466_18 
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.38.33130-h82b7239_18 
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.38.33130-hcb4865c_18 
  wheel              conda-forge/noarch::wheel-0.43.0-pyhd8ed1ab_1 
  xz                 pkgs/main/win-64::xz-5.4.6-h8cc25b3_0 

Error: Error creating conda environment 'r-reticulate' [exit code 1]

**Comment by olugovoy** [comment]
Thanks @sourishju!
One of potential solution is to skip the installation step, check:
[miniconda_path](https://rstudio.github.io/reticulate/reference/miniconda_path.html)()
And if it exists, then move to the next step:
[Create ideea environment](https://ideea-model.github.io/IDEEA/articles/install.html#create-ideea-environment).

If this doesn't work, please check which Python is default on your system:
py_discover_config()
and existing environments:
[conda_list](https://rstudio.github.io/reticulate/reference/conda-tools.html)()

**Comment by sourishju** [comment]
Yes, I have just skipped that step and it works
